export const categories = [
  { id: "appearance", title: "Внешность", description: "Вид и подача" },
  { id: "hygiene", title: "Гигиена", description: "Уход и свежесть" },
  { id: "communication", title: "Общение", description: "Диалоги и переписка" },
  { id: "social", title: "Адекватность", description: "Границы и уважение" },
  { id: "confidence", title: "Уверенность", description: "Спокойствие и самооценка" },
  { id: "home", title: "Быт", description: "Самостоятельность дома" },
  { id: "lifestyle", title: "Образ жизни", description: "Режим и привычки" },
  { id: "money", title: "Деньги", description: "Расходы и понты" },
  { id: "internet", title: "Интернет", description: "Соцсети и кринж" },
  { id: "gaming", title: "Игры", description: "Катки и последствия" },
  { id: "absurd", title: "Абсурд", description: "Бытовой сюр" },
  { id: "date", title: "Свидание", description: "Поведение при встрече" }
];

const r = (id, category, tone, title, effect, weight, def = 5, hint = "") => ({
  id, category, tone, title, type: "range", min: 1, max: 10, default: def, effect, weight, hint
});

const b = (id, category, tone, title, yesScore, noScore, def = false, hint = "") => ({
  id, category, tone, title, type: "boolean", default: def, yesScore, noScore, weight: Math.max(Math.abs(yesScore), Math.abs(noScore)), hint
});

const n = (id, category, tone, title, scorer, weight, def, min, max, unit = "", hint = "") => ({
  id, category, tone, title, type: "number", scorer, weight, default: def, min, max, unit, hint
});

const s = (id, category, tone, title, weight, options, def = 0, hint = "") => ({
  id, category, tone, title, type: "select", weight, options, default: def, hint
});

export const questions = [
  // Внешность и стиль
  n("age", "appearance", "serious", "Возраст", "age", 12, 18, 14, 60, "лет", "Если меньше 18, результат считается как шанс нормального общения со сверстниками."),
  n("height", "appearance", "serious", "Рост", "height", 9, 178, 140, 220, "см", "Рост влияет, но не решает все. Алгоритм специально не делает из него главного босса."),
  r("posture", "appearance", "serious", "Осанка: держишься ровно, а не складываешься в знак вопроса", "positive", 7, 6),
  r("haircut_fit", "appearance", "serious", "Стрижка выглядит специально выбранной, а не случайно выданной жизнью", "positive", 8, 6),
  r("clothes_fit", "appearance", "serious", "Одежда сидит по размеру", "positive", 8, 6),
  r("style_score", "appearance", "serious", "Стиль выглядит собранно, а не как случайный набор вещей", "ideal", 7, 6, "Слишком стерильно тоже странно. Идеал где-то между 'нормально' и 'есть вкус'."),
  r("shoe_clean", "appearance", "serious", "Обувь выглядит чистой, а не прошла войну с тротуаром", "positive", 7, 6),
  r("smile", "appearance", "serious", "Улыбка выглядит дружелюбно, а не как у школьного злодея", "positive", 7, 6),
  r("photo_quality", "appearance", "serious", "Фото в соцсетях не выглядят как кадры с камеры подъезда", "positive", 7, 5),
  r("face_grooming", "appearance", "serious", "Лицо выглядит ухоженно", "positive", 8, 6),
  r("skin_care", "appearance", "serious", "Уход за кожей без фанатизма", "ideal", 5, 5, "Ноль ухода плохо. Лаборатория из 40 баночек тоже пугает."),
  r("body_shape", "appearance", "serious", "Физическая форма", "positive", 7, 5),
  r("voice", "appearance", "mixed", "Голос звучит спокойно, а не как плохой микрофон в голосовом чате", "positive", 5, 5),
  s("beard", "appearance", "serious", "Борода", 6, [
    { label: "Нет бороды", score: 2 },
    { label: "Есть и ухоженная", score: 6 },
    { label: "Есть, но живет по своим законам", score: -5 },
    { label: "Усы школьного злодея", score: -4 },
    { label: "Борода выглядит как отдельная деталь, которую приклеили утром", score: 1 }
  ], 0),
  b("same_hoodie_week", "appearance", "funny", "Одна и та же худи уже знает твой пароль от Wi-Fi", -7, 3, false),
  b("sunglasses_inside", "appearance", "funny", "Очки в помещении нужны для загадочности", -5, 2, false),
  b("mirror_lift_only", "appearance", "funny", "Все фото сделаны в лифте, как будто ты там живешь", -6, 2, false),
  b("anime_pose_photo", "appearance", "funny", "На фото позируешь так, будто сейчас начнется аниме-драка", -4, 2, false),
  b("shirt_with_wolf", "appearance", "funny", "Футболка с волком кажется тебе одеждой на любой случай", -5, 2, false),

  // Гигиена
  r("shower_frequency", "hygiene", "serious", "Душ — это регулярная привычка, а не редкое событие", "positive", 12, 7),
  r("teeth", "hygiene", "serious", "Зубы чистятся регулярно, как будто у них есть будущее", "positive", 12, 7),
  r("deodorant", "hygiene", "serious", "Дезодорант используется по назначению", "positive", 9, 7),
  r("perfume_amount", "hygiene", "serious", "Парфюм используется умеренно, а не как химическая атака", "ideal", 6, 5, "Идеал в середине. 10/10 тут означает газовую атаку."),
  r("nails", "hygiene", "serious", "Ногти выглядят чисто, а не как улика из криминального сериала", "positive", 8, 6),
  r("laundry", "hygiene", "serious", "Одежда чистая", "positive", 10, 7),
  r("bed_sheets", "hygiene", "serious", "Постельное белье меняется до того, как его можно изучать в музее", "positive", 7, 5),
  r("hair_wash", "hygiene", "serious", "Волосы моются вовремя и выглядят нормально", "positive", 9, 7),
  r("socks_change", "hygiene", "serious", "Носки меняются вовремя, пока они не начали жить отдельно", "positive", 8, 7),
  b("smell_test_clothes", "hygiene", "funny", "Проверяешь одежду нюхом и называешь это диагностикой", -10, 4, false),
  b("two_in_one_everything", "hygiene", "funny", "Один флакон для волос, тела, посуды и моральной поддержки", -5, 2, false),
  b("towel_ancient", "hygiene", "funny", "Полотенце видело больше эпох, чем учебник истории", -7, 3, false),
  b("axe_cloud", "hygiene", "funny", "Спрей заменяет душ, молитву и здравый смысл", -10, 4, false),
  b("pillow_yellow", "hygiene", "funny", "Подушка уже не белая и просит пенсию", -8, 3, false),
  b("sock_floor_map", "hygiene", "funny", "Носки по комнате лежат так, будто это схема метро", -6, 3, false),

  // Общение
  r("listening", "communication", "serious", "Умеешь слушать, а не просто ждешь свою очередь говорить", "positive", 12, 6),
  r("questions_skill", "communication", "serious", "Задаешь вопросы с интересом, а не как следователь", "positive", 9, 6),
  r("humor", "communication", "serious", "Чувство юмора", "positive", 9, 6),
  r("serious_talk", "communication", "serious", "Можешь говорить серьезно и не превращать это в длинную лекцию", "positive", 7, 5),
  r("light_talk", "communication", "serious", "Легкий разговор не заканчивается неловким молчанием", "positive", 8, 6),
  r("compliments", "communication", "serious", "Комплименты звучат естественно и без странного подтекста", "positive", 8, 5),
  r("argument_level", "communication", "serious", "Споришь так, будто защищаешь диплом по каждой мелочи", "negative", 8, 4),
  r("interrupts", "communication", "serious", "Перебиваешь собеседника", "negative", 9, 3),
  r("voice_messages", "communication", "mixed", "Голосовые сообщения не превращаются в длинный подкаст", "ideal", 5, 4, "1 — почти нет голосовых, 10 — выпускаешь аудиокниги."),
  n("reply_minutes", "communication", "mixed", "Среднее время ответа", "replyMinutes", 6, 35, 0, 1440, "мин", "Моментально 24/7 и через сутки без причины оба варианта могут портить вайб."),
  r("message_spam", "communication", "mixed", "Сообщений подряд без ответа", "negative", 8, 3),
  b("starts_with_ku", "communication", "funny", "Начинаешь переписку словом 'ку' и считаешь, что этого достаточно", -4, 2, false),
  b("writes_pon", "communication", "funny", "На большой текст отвечаешь 'пон'", -8, 3, false),
  b("former_talk", "communication", "serious", "Рассказываешь про бывшую на старте общения", -12, 4, false),
  b("baby_after_4_msgs", "communication", "funny", "Называешь человека 'малышка' почти сразу после знакомства", -10, 4, false),
  b("deep_quote_mode", "communication", "funny", "После отказа начинаешь писать грустные философские сообщения", -9, 3, false),
  b("can_say_sorry", "communication", "serious", "Умеешь нормально извиниться без 'ну извини если что'", 8, -8, true),
  b("can_make_plans", "communication", "serious", "Можешь предложить конкретный план встречи", 8, -6, true),
  b("sends_only_stickers", "communication", "funny", "В трудный момент отправляешь стикер вместо мысли", -5, 2, false),
  b("good_morning_ritual", "communication", "funny", "Каждое утро пишешь 'доброе утро' так, будто сдаешь отчет", -3, 2, false),

  // Социальная адекватность
  b("respects_boundaries", "social", "serious", "Уважаешь личные границы", 18, -40, true, "Это главный красный флаг. При ответе 'нет' итог жестко ограничивается."),
  b("accepts_no", "social", "serious", "Спокойно принимаешь отказ", 18, -45, true, "Самый важный пункт во всей анкете."),
  r("jealousy", "social", "serious", "Ревность к каждому лайку", "negative", 12, 3),
  r("control_level", "social", "serious", "Желание контролировать чужие соцсети", "negative", 14, 2),
  r("aggression", "social", "serious", "Агрессия в конфликте", "negative", 14, 2),
  r("empathy", "social", "serious", "Эмпатия", "positive", 11, 6),
  r("respectful_jokes", "social", "serious", "Шутишь без унижения других", "positive", 8, 6),
  b("girls_same", "social", "serious", "Говоришь 'все девушки одинаковые' и сам не слышишь сирену", -16, 5, false),
  b("alpha_talk", "social", "funny", "Называешь себя альфой всерьез", -14, 4, false),
  b("sigma_talk", "social", "funny", "Слово 'сигма' используешь всерьез", -12, 3, false),
  b("waiter_panic", "social", "mixed", "Когда подходит официант, у тебя начинается внутренняя паника", -7, 4, false),
  b("public_polite", "social", "serious", "Вежливо общаешься с персоналом", 9, -9, true),
  b("explains_joke", "social", "funny", "После неудачной шутки начинаешь объяснять ее и делаешь только хуже", -5, 2, false),
  b("apology_with_but", "social", "serious", "Извинение заканчивается словом 'но'", -8, 3, false),

  // Уверенность
  r("confidence", "confidence", "serious", "Уверенность в себе", "ideal", 10, 7, "10/10 может выглядеть как самовлюбленность. Алгоритм любит уверенность без цирка."),
  r("calmness", "confidence", "serious", "Спокойствие", "positive", 8, 6),
  r("need_to_prove", "confidence", "serious", "Постоянно доказываешь, что ты крутой", "negative", 8, 3),
  r("fear_silence", "confidence", "serious", "Боишься пауз в разговоре", "negative", 6, 4),
  r("mystery_act", "confidence", "funny", "Пытаешься выглядеть загадочным, но получается просто молчаливо", "negative", 7, 3),
  b("sad_after_delay", "confidence", "funny", "Пишешь 'ладно, я понял...' после трех минут без ответа", -10, 4, false),
  b("can_lose_argument", "confidence", "serious", "Можешь спокойно проиграть спор", 8, -8, true),
  b("hood_up_outside", "confidence", "funny", "Ходишь в капюшоне так, будто ты финальный босс двора", -4, 2, false),
  b("asks_directly", "confidence", "serious", "Можешь спокойно предложить встретиться", 8, -5, true),
  b("main_character_music", "confidence", "funny", "Идешь по улице с видом, будто про тебя снимают трейлер", -3, 2, false),
  b("afraid_to_order", "confidence", "mixed", "Заказать еду вслух для тебя сложнее, чем экзамен", -6, 3, false),

  // Быт
  r("cooking", "home", "serious", "Умеешь готовить", "positive", 9, 5),
  b("can_cook_eggs", "home", "mixed", "Можешь пожарить яйца без пожарной драмы", 7, -7, true),
  r("clean_room", "home", "serious", "Комната выглядит как нормальное место для жизни", "positive", 10, 5),
  b("chair_wardrobe", "home", "funny", "Стул в комнате используется как шкаф", -8, 3, false),
  b("cups_colony", "home", "funny", "Грязные кружки стоят так долго, что могли бы создать цивилизацию", -9, 3, false),
  b("washing_machine", "home", "serious", "Понимаешь, как пользоваться стиральной машиной", 8, -8, true),
  b("knows_documents", "home", "mixed", "Знаешь, где лежит паспорт", 6, -6, true),
  b("can_buy_groceries", "home", "serious", "Можешь купить продукты по списку и не принести только чипсы", 7, -5, true),
  b("trash_out", "home", "mixed", "Можешь вынести мусор без долгих внутренних переговоров", 6, -5, true),
  b("bed_change_tutorial", "home", "funny", "Чтобы сменить постельное белье, тебе нужен видеоурок", -7, 3, false),
  b("only_dumplings", "home", "funny", "Рацион: пельмени, энергетик и надежда", -8, 3, false),
  r("room_smell", "home", "serious", "В комнате нормальный запах, можно зайти без подготовки", "positive", 8, 6),
  b("fridge_has_one_sauce", "home", "funny", "В холодильнике живет один соус и холодный воздух", -5, 2, false),
  b("dish_pyramid", "home", "funny", "Посуду моешь только когда она строит пирамиду", -7, 3, false),
  b("laundry_basket_boss", "home", "funny", "Корзина с бельем переполнена и уже пугает", -5, 2, false),

  // Образ жизни
  n("sleep_hours", "lifestyle", "serious", "Средний сон", "sleepHours", 8, 7, 0, 16, "ч", "Идеал не 14 часов. Алгоритм ищет живого человека, а не спящего босса."),
  r("sport", "lifestyle", "serious", "Физическая активность", "positive", 8, 5),
  r("walks", "lifestyle", "serious", "Выходишь на улицу не только чтобы забрать доставку", "positive", 6, 5),
  r("goals", "lifestyle", "serious", "Есть понятные цели", "positive", 8, 5),
  r("study_work", "lifestyle", "serious", "Учеба или работа находятся под контролем", "positive", 8, 5),
  r("phone_addiction", "lifestyle", "serious", "Проверяешь телефон слишком часто", "negative", 7, 4),
  r("energy_drinks", "lifestyle", "mixed", "Пьешь энергетики вместо нормальной воды", "negative", 6, 3),
  b("sleep_is_weakness", "lifestyle", "funny", "Говоришь 'сон для слабых', а потом слабый сам", -7, 3, false),
  b("can_evening_without_pc", "lifestyle", "serious", "Можешь провести вечер без компьютера", 6, -5, true),
  b("outside_quest", "lifestyle", "funny", "Выход на улицу ощущается как отдельное испытание", -6, 3, false),
  r("hobby_quality", "lifestyle", "serious", "Есть нормальное хобби, о котором можно рассказать", "positive", 6, 5),
  b("wakes_at_dinner", "lifestyle", "funny", "Просыпаешься к ужину и называешь это режимом", -6, 2, false),
  b("water_is_myth", "lifestyle", "funny", "Вода для тебя это жидкость внутри энергетика", -7, 3, false),

  // Деньги
  r("money_stability", "money", "serious", "Финансовая стабильность", "positive", 7, 5),
  r("money_management", "money", "serious", "Умеешь распоряжаться деньгами", "positive", 8, 5),
  r("money_flex", "money", "serious", "Хвастаешься деньгами", "negative", 8, 3),
  b("can_pay_coffee", "money", "mixed", "Можешь спокойно оплатить кофе без финансовой паники", 6, -5, true),
  b("microloan_donate", "money", "funny", "Микрозайм ради доната кажется тебе рабочим планом", -14, 5, false),
  b("crypto_investor_300", "money", "funny", "Называешь себя инвестором, имея 300 рублей в крипте", -8, 3, false),
  r("gift_pressure", "money", "mixed", "Даришь подарки слишком рано и слишком навязчиво", "negative", 5, 3),
  b("buys_skins_over_food", "money", "funny", "Скины важнее еды", -9, 3, false),
  b("saves_for_goal", "money", "serious", "Копишь на понятную цель", 5, -3, true),
  b("card_declined_panic", "money", "funny", "Перед оплатой заранее боишься фразы 'карта отклонена'", -4, 2, false),
  b("rich_mindset", "money", "funny", "Говоришь 'мышление богатого', когда покупаешь дошик по акции", -5, 2, false),

  // Интернет-кринж
  s("avatar_type", "internet", "mixed", "Аватарка", 8, [
    { label: "Нормальное фото", score: 7 },
    { label: "Мем, но без психоза", score: 2 },
    { label: "Аниме с кровью", score: -7 },
    { label: "Черный фон и цитата", score: -8 },
    { label: "Машина не твоя", score: -6 },
    { label: "Фото где видно только подбородок", score: -4 }
  ], 0),
  r("story_drama", "internet", "mixed", "Грустные сторис каждый день", "negative", 8, 3),
  r("comment_wars", "internet", "mixed", "Споришь в комментариях часами", "negative", 8, 3),
  b("joker_quotes", "internet", "funny", "Репостишь цитаты Джокера как юридический документ", -9, 4, false),
  b("lonely_wolf_status", "internet", "funny", "В статусе 'одинокий волк'", -8, 3, false),
  b("business_tg", "internet", "funny", "Твой Telegram-профиль выглядит как страница продавца успеха", -7, 3, false),
  b("dark_lord_nick", "internet", "funny", "Ник выглядит как dark_lord_228 или что-то похожее", -7, 3, false),
  b("face_visible_photo", "internet", "serious", "Есть хотя бы одно нормальное фото лица", 7, -7, true),
  b("phone_face_photo", "internet", "funny", "На каждом фото лицо закрыто телефоном, как свидетель в суде", -6, 3, false),
  b("woman_should_posts", "internet", "serious", "Пишешь посты в стиле 'женщина должна'", -18, 6, false),
  b("ai_generated_bio", "internet", "funny", "Описание профиля выглядит как мотивационная цитата без души", -5, 2, false),
  r("meme_language", "internet", "mixed", "Говоришь только мемами", "ideal", 5, 5, "Мемы норм, но человек должен уметь говорить словами."),
  r("screen_time", "internet", "mixed", "Экранное время", "screenTime", 6, 6, "После определенной точки телефон начинает есть рейтинг."),
  b("private_channel_diary", "internet", "funny", "Ведешь закрытый канал, где драматично страдаешь для пары друзей", -4, 2, false),
  b("spotify_sad_public", "internet", "funny", "Публичный плейлист выглядит как дневник самого грустного человека района", -5, 2, false),
  b("linkedin_at_16", "internet", "funny", "Пишешь про бизнес-мышление, хотя бизнеса пока нет", -5, 2, false),

  // Игры
  n("dota_mmr", "gaming", "funny", "MMR в Dota 2", "dotaMmr", 12, 0, 0, 13000, "MMR", "Высокий MMR не всегда минус. Если остальная жизнь в порядке, будет странный бонус дисциплины."),
  n("dota_hours", "gaming", "funny", "Часов в Dota 2", "gameHours", 10, 0, 0, 20000, "ч"),
  s("dota_hero", "gaming", "funny", "Main-герой в Dota", 9, [
    { label: "Не играю", score: 8 },
    { label: "Pudge", score: -9 },
    { label: "Invoker", score: -6 },
    { label: "Shadow Fiend", score: -5 },
    { label: "Crystal Maiden", score: 2 },
    { label: "Techies", score: -10 },
    { label: "Любой саппорт", score: 4 },
    { label: "Meepo, потому что обычной жизни мало", score: -7 }
  ], 0),
  r("dota_toxic", "gaming", "funny", "Токсичность в голосовом чате", "negative", 12, 2),
  b("says_team_ruins", "gaming", "funny", "Говоришь 'тиммейты виноваты' чаще, чем признаешь свои ошибки", -8, 3, false),
  b("ez_after_win", "gaming", "funny", "Пишешь 'ez' после победы и думаешь, что это харизма", -6, 3, false),
  b("date_after_game", "gaming", "funny", "Перед встречей говоришь 'щас катку доиграю'", -10, 4, false),
  b("arcana_over_gift", "gaming", "funny", "Игровая покупка кажется важнее нормального подарка", -8, 3, false),
  n("cs_hours", "gaming", "funny", "Часов в CS2", "gameHoursSoft", 7, 0, 0, 15000, "ч"),
  r("cs_rage", "gaming", "funny", "После каждой смерти сразу кричишь 'читер'", "negative", 6, 3),
  b("skins_over_jacket", "gaming", "funny", "Скины дороже куртки", -6, 3, false),
  b("genshin_donate", "gaming", "funny", "Донат в гачу прячешь даже от собственной совести", -6, 2, false),
  b("minecraft_server", "gaming", "funny", "Есть свой сервер Minecraft", 3, 0, false),
  b("dirt_house", "gaming", "funny", "В Minecraft строишь дом из земли и называешь это базой", -4, 2, false),
  b("hoi4_1000", "gaming", "funny", "1000+ часов в Hearts of Iron IV", -8, 3, false),
  b("explains_history_with_hoi", "gaming", "funny", "Объясняешь историю через карту из Hearts of Iron IV", -6, 3, false),
  b("lol_player", "gaming", "funny", "Играешь в League of Legends и говоришь, что спокойный", -8, 3, false),
  b("roblox_over_16", "gaming", "funny", "Roblox после 16 без объяснений", -5, 2, false),
  b("discord_mod_energy", "gaming", "funny", "В Discord ведешь себя как модератор, которому дали слишком много власти", -7, 3, false),
  b("one_more_game_lie", "gaming", "funny", "'Еще одна катка' у тебя означает исчезновение на вечер", -8, 3, false),

  // Абсурд
  b("hospital_without_mom", "absurd", "funny", "Ходишь в больницу без мамы", 8, -10, true),
  b("can_pick_order", "absurd", "funny", "Можешь сам забрать заказ у курьера без попытки спрятаться", 5, -5, true),
  b("ask_directions", "absurd", "funny", "Можешь спросить дорогу у прохожего без паники", 5, -5, true),
  b("open_door_courier", "absurd", "funny", "Открываешь дверь курьеру без внутренней борьбы", 5, -5, true),
  b("call_delivery", "absurd", "funny", "Можешь позвонить в доставку и спокойно объяснить проблему", 5, -6, true),
  b("thank_cashier", "absurd", "mixed", "Говоришь кассиру 'спасибо' нормальным голосом", 5, -5, true),
  b("buy_condoms_no_stealth", "absurd", "funny", "Можешь купить презервативы без режима секретного агента", 6, -6, true),
  b("choose_shampoo", "absurd", "funny", "Можешь выбрать шампунь без 20 минут изучения полки", 5, -4, true),
  b("handcream_sourcream", "absurd", "funny", "Понимаешь разницу между кремом для рук и едой", 4, -5, true),
  b("book_barber", "absurd", "funny", "Можешь сам записаться к парикмахеру", 6, -6, true),
  b("barber_fear", "absurd", "funny", "Боишься записаться к парикмахеру сильнее, чем сходить к врачу", -6, 3, false),
  b("knows_size", "absurd", "mixed", "Знаешь размер своей одежды", 5, -5, true),
  b("knows_address", "absurd", "mixed", "Можешь назвать свой полный адрес без подсказок", 4, -4, true),
  b("remembers_mom_bday", "absurd", "mixed", "Помнишь день рождения мамы", 4, -4, true),
  b("password_memory", "absurd", "funny", "Помнишь пароль хотя бы от важных аккаунтов", 4, -3, true),
  b("keys_week", "absurd", "funny", "Можешь неделю не терять ключи", 5, -5, true),
  b("can_iron", "absurd", "mixed", "Утюг для тебя обычный прибор, а не страшный механизм", 4, -3, false),
  b("open_jar", "absurd", "funny", "Можешь открыть банку без командной операции", 4, -3, true),
  b("fridge_quiet", "absurd", "funny", "Ночью закрываешь холодильник тихо, а не как спецназ", 4, -4, true),
  b("find_trash", "absurd", "mixed", "Знаешь, где дома мусорка, и иногда ею пользуешься", 4, -4, true),
  b("movie_choice", "absurd", "mixed", "Можешь выбрать фильм быстрее, чем за 50 минут", 5, -4, true),
  b("scp_date", "absurd", "funny", "На свидании мог бы включить ролик про страшные теории вместо разговора", -7, 3, false),
  b("crypto_lecture", "absurd", "funny", "Начинаешь рассказывать про крипту, даже если никто не спрашивал", -8, 3, false),
  b("too_smart_school", "absurd", "funny", "Говоришь 'я слишком умный для школы'", -7, 3, false),
  b("rude_introvert", "absurd", "funny", "Называешь грубость интроверсией", -8, 3, false),
  b("im_different", "absurd", "funny", "Пишешь 'я другой', хотя отличается только ник", -6, 2, false),
  b("silence_mystery", "absurd", "funny", "Думаешь, что молчание делает тебя загадочным", -5, 2, false),
  b("no_baza_day", "absurd", "funny", "Можешь прожить день без слова 'база'", 4, -4, true),
  b("windows_reinstall_it", "absurd", "funny", "Называешь себя айтишником после одной переустановки Windows", -5, 2, false),
  b("script_final_final", "absurd", "funny", "Твои файлы называются вроде script_final_final_2_REAL.py", -3, 2, false),
  b("microwave_timer", "absurd", "funny", "Оставляешь на микроволновке 0:01 и считаешь, что это нормально", -4, 2, false),
  b("elevator_silence_boss", "absurd", "funny", "В лифте с соседом смотришь в пол, как будто там титры", -4, 2, false),
  b("adult_call_fear", "absurd", "funny", "Звонок в регистратуру кажется страшнее хоррора", -5, 2, false),
  b("fork_in_sink", "absurd", "funny", "Одна вилка в раковине быстро превращается в гору посуды", -3, 2, false),

  // Свидание
  b("can_choose_place", "date", "serious", "Можешь выбрать место встречи", 8, -7, true),
  b("mall_romance", "date", "funny", "Торговый центр кажется тебе романтическим местом", -6, 3, false),
  b("walk_minus_10", "date", "funny", "Предлагаешь гулять по району в мороз", -7, 3, false),
  r("punctuality", "date", "serious", "Приходишь вовремя", "positive", 8, 6),
  b("near_40_min", "date", "funny", "Опаздываешь на 40 минут и пишешь 'я почти рядом'", -10, 4, false),
  r("phone_on_date", "date", "serious", "Сидишь в телефоне на встрече", "negative", 9, 3),
  r("talks_about_self", "date", "serious", "Говоришь только о себе", "negative", 8, 4),
  b("splits_coffee_weird", "date", "mixed", "Просишь вернуть деньги за кофе слишком официально и неловко", -5, 2, false),
  b("bad_compliment", "date", "funny", "Делаешь комплимент, который звучит как оскорбление", -10, 4, false),
  b("asks_exes", "date", "serious", "Спрашиваешь про бывших слишком рано", -9, 3, false),
  b("love_after_30", "date", "funny", "Признаешься в чувствах через 30 минут", -8, 3, false),
  b("home_movie_too_early", "date", "serious", "Слишком рано зовешь домой 'просто посмотреть фильм'", -10, 4, false),
  b("can_say_goodbye", "date", "serious", "Можешь спокойно попрощаться", 6, -5, true),
  b("liked_me_question", "date", "funny", "Сразу после встречи спрашиваешь 'ну что, я тебе понравился?'", -8, 3, false),
  b("sad_playlist", "date", "funny", "После отказа отправляешь грустный плейлист", -7, 3, false),
  b("normal_pace", "date", "serious", "Не торопишь события и уважаешь комфортный темп общения", 9, -9, true),
  b("can_pay_attention", "date", "serious", "На встрече слушаешь человека, а не только ждешь свою реплику", 9, -8, true),
  r("date_budget_balance", "date", "serious", "Бюджет свидания разумный: без понтов и без боли для кошелька", "ideal", 5, 5),
  r("initiative", "date", "serious", "Инициатива", "ideal", 7, 6, "Полное отсутствие инициативы плохо. Давление тоже плохо."),
  r("awkwardness", "date", "mixed", "Неловкость на встрече", "ideal", 4, 5, "Ноль неловкости подозрительно. Десять неловкости уже авария."),
  b("orders_for_her", "date", "serious", "Заказываешь за другого человека без спроса", -8, 3, false),
  b("weather_smalltalk_only", "date", "funny", "Разговор держится только на погоде и неловких паузах", -5, 2, false),
  b("brings_friend", "date", "funny", "На встречу мог бы прийти с другом для моральной поддержки", -10, 4, false),
  b("first_date_resume", "date", "funny", "На первом свидании задаешь вопросы как на собеседовании: цели, планы и почему выбрали именно тебя", -7, 3, false)
];
